// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi2GAP7_uspj2SRjbzl64E-Fr_9wmY518',
    appId: '1:929002774991:web:c1e1ae45f64301a11ab2ba',
    messagingSenderId: '929002774991',
    projectId: 'jr-design-project',
    authDomain: 'jr-design-project.firebaseapp.com',
    storageBucket: 'jr-design-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR8vvQWrS9mNVoER349BICPUjyUT9mK-g',
    appId: '1:929002774991:android:50b941b3e8d2d60b1ab2ba',
    messagingSenderId: '929002774991',
    projectId: 'jr-design-project',
    storageBucket: 'jr-design-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCyPwUeLrzgjROpWZKpjInbq_M-HjcRss',
    appId: '1:929002774991:ios:4f408fb651d5b0861ab2ba',
    messagingSenderId: '929002774991',
    projectId: 'jr-design-project',
    storageBucket: 'jr-design-project.firebasestorage.app',
    iosBundleId: 'com.example.projectDemo',
  );
}
